### ISSUE TITLE
提问问题后终端报错

### ISSUE THREAD

**Issue by MapleLeeLee** [MuBai-He/ChatWaifu-marai#15]
大佬我问完问题后chatgpt的问题一直在输入框不发送，然后终端报了这个错。
Exception in thread Thread-2 (__call):
Traceback (most recent call last):
  File "D:\Software\anaconda3\envs\chatWaifu\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Software\anaconda3\envs\chatWaifu\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Software\anaconda3\envs\chatWaifu\lib\site-packages\miraicle\threadpool.py", line 30, in __call
    func(*args)
  File "D:\Software\anaconda3\envs\chatWaifu\lib\site-packages\miraicle\mirai.py", line 209, in __call_plugins
    func(self, msg)
  File "E:\ChatWaifu-marai\mirai\ChatWaifu-marai-main\ChatWaifu_marai.py", line 373, in reply_to_group
    resp = api.send_message(text)
  File "D:\Software\anaconda3\envs\chatWaifu\lib\site-packages\pyChatGPT\pyChatGPT.py", line 444, in send_message
    response = self.driver.find_elements(*chatgpt_small_response)[-1]
IndexError: list index out of range

**Comment by MuBai-He** [comment]
重新运行几次试试，好像和pychatgpt有关
