### ISSUE TITLE
我想问一下这个报错是怎么回事

### ISSUE THREAD

**Issue by FantasyWD** [MuBai-He/ChatWaifu-marai#17]
[2023-02-02 22:25:33.607] host.py (273) - [ERROR] : 插件ChatWaifu触发事件normal_message_responded时发生错误
[2023-02-02 22:25:33.609] host.py (274) - [ERROR] : Traceback (most recent call last):
  File "C:\Users\86181\Documents\chatbot\QQbot\bot\QChatGPT\.\pkg\plugin\host.py", line 263, in emit
    hook(plugin['instance'], **kwargs)
  File "C:\Users\86181\Documents\chatbot\QQbot\bot\QChatGPT\.\plugins\QchatPlugins-master\ChatWaifu\main.py", line 33, in group_normal_message_received
    kwargs['host'].send_group_message(kwargs["launcher_id"], msg)
  File "C:\Users\86181\Documents\chatbot\QQbot\bot\QChatGPT\.\pkg\plugin\host.py", line 232, in send_group_message
    asyncio.run(self.get_bot().send_group_message(group, message))
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "C:\Users\86181\Documents\chatbot\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 415, in __call__
    return await self.set(*args, **kwargs)
  File "C:\Users\86181\Documents\chatbot\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 383, in set
    return await self._call_api(
  File "C:\Users\86181\Documents\chatbot\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 373, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "C:\Users\86181\Documents\chatbot\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 304, in call
    raw_response = await api_provider.call_api(
  File "C:\Users\86181\Documents\chatbot\QQbot\bot\python\lib\site-packages\mirai\bot.py", line 91, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "C:\Users\86181\Documents\chatbot\QQbot\bot\python\lib\site-packages\mirai\adapters\websocket.py", line 236, in call_api
    return await self._recv(sync_id)
  File "C:\Users\86181\Documents\chatbot\QQbot\bot\python\lib\site-packages\mirai\adapters\websocket.py", line 165, in _recv
    raise exceptions.ApiError(data)
mirai.exceptions.ApiError: (5, '[ERROR 5]发送消息目标不存在，或指定对象不存在。', '指定对象不存在')

**Comment by FantasyWD** [comment]
而且机器人大概率会在结尾加一句需要使用！help获取帮助吗，像是“我可以帮助你解决各种问题，请输入!help来获得更多信息”

**Comment by ygmz233** [comment]
！help的问题在qchatgpt里面的config.py里改一下默认设定就行了（default_prompt）
