### ISSUE TITLE
在网页ChatGPT做出回复后，出现报错

### ISSUE THREAD

**Issue by czhang13-ua** [MuBai-He/ChatWaifu-marai#36]
流程及报错信息如下：
2023-04-21 19:34:00 GroupMessage #20 （群号）: '[At:QQ号] 你是谁？'
2023-04-21 19:33:56 GroupMessage #21 - 群号 <- '正在处理中请稍后...'
Exception in thread Thread-2 (__call):
Traceback (most recent call last):
  File "D:\anaconda3\envs\chatWaifu\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\anaconda3\envs\chatWaifu\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\anaconda3\envs\chatWaifu\lib\site-packages\miraicle\threadpool.py", line 30, in __call
    func(*args)
  File "D:\anaconda3\envs\chatWaifu\lib\site-packages\miraicle\mirai.py", line 209, in __call_plugins
    func(self, msg)
  File "D:\xunlei\ChatWaifu\mirai\ChatWaifu-marai\ChatWaifu_marai.py", line 383, in reply_to_group
    resp = api.send_message(text)
  File "D:\anaconda3\envs\chatWaifu\lib\site-packages\pyChatGPT\pyChatGPT.py", line 460, in send_message
    conversation_id = matches.group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by czhang13-ua** [comment]
网上debug说的都是search()和match()的问题，也和这个报错对不上。
大佬求帮助，感谢

**Comment by MuBai-He** [comment]
pychatgpt这个库的问题，那个作者好像不维护了

**Comment by czhang13-ua** [comment]
> pychatgpt这个库的问题，那个作者好像不维护了

那现在还有解决的办法么大佬

**Comment by MuBai-He** [comment]
暂时等着API我做完看看发布下
